### ISSUE TITLE
Statistics from index node

### ISSUE THREAD

**Issue by cmourzelas** [criteo/mewpoke#42]
Hello,

The exporter seems to be enable to connect to index node in a couchbase cluster.

[main] ERROR com.criteo.nosql.mewpoke.couchbase.CouchbaseMonitor - Cannot fetch stat timestamp for bucket xxxxxxx and node xxx.xxx.xx.xxx:8091.
java.lang.NullPointerException
        at com.criteo.nosql.mewpoke.couchbase.CouchbaseMonitor.collectApiStatsBucket(CouchbaseMonitor.java:236)
        at java.util.Optional.map(Optional.java:215)
        at com.criteo.nosql.mewpoke.couchbase.CouchbaseRunnerStats.lambda$poke$0(CouchbaseRunnerStats.java:20)
        at java.util.HashMap.forEach(HashMap.java:1288)
        at com.criteo.nosql.mewpoke.couchbase.CouchbaseRunnerStats.poke(CouchbaseRunnerStats.java:16)
        at com.criteo.nosql.mewpoke.couchbase.CouchbaseRunnerAbstract.dispatch_events(CouchbaseRunnerAbstract.java:92)
        at com.criteo.nosql.mewpoke.couchbase.CouchbaseRunnerAbstract.run(CouchbaseRunnerAbstract.java:49)
        at com.criteo.nosql.mewpoke.Main.main(Main.java:58)

Have you an idea about that ? 
Thanks

**Comment by erebe** [comment]
Sorry for the late response, I haven't got the mail regarding your issue.
What do you call an `index node` ? We are mainly using Couchbase for its KV persistent value store.

**Comment by cmourzelas** [comment]
Hello, 

We use N1QL and we have index/query node in our cluster.

**Comment by erebe** [comment]
Hello,
Sadly our liscence forbid us to use N1QL on Couchbase, so I can't help you with that.
If you are willing to make a PR for that I will accept it gladly.

As of today, you are using the couchbase api in order to retrieves stats. I don't if an other api is available for those nodes.
